Console.WriteLine("Welcome to Carpet Cleaning Service");
Console.WriteLine("Enter the number of small carpets to be cleaned:");
int Number_small = Convert.ToInt32(Console.ReadLine()!);
Console.WriteLine("Enter the number of large carpets to be cleaned:"); ;
int Number_large = Convert.ToInt32(Console.ReadLine()!);
double Price_small = 25.00;
double Price_large = 35.00;
double Cost = (Number_small * Price_small) + (Number_large * Price_large);
double Tax = 0.06 * Cost;
double Total_Tax = Cost + Tax;
Console.WriteLine("Estimate for carpet cleaning service");
Console.WriteLine($"Number of small carpets: {Number_small}");
Console.WriteLine($"Number of large carpets: {Number_large}");
Console.WriteLine($"Price per small room:  {Price_small:C}");
Console.WriteLine($"Price per large room:  {Price_large:C}");
Console.WriteLine($"Cost:  {Cost:C}");
Console.WriteLine($"Tax:  {Tax:C}");
Console.WriteLine($"=================================");
Console.WriteLine($"Total estimate:  {Total_Tax:C}");
Console.WriteLine($"This estimate is valid for 30 days");
